APP_ADMIN_PASSWORD = "super-strong-gate"

MYSQL_HOST = "127.0.0.1"
MYSQL_PORT = 3306
MYSQL_USER = "root"
MYSQL_PASSWORD = "Aaadd@1986"
MYSQL_DB = "landbridge"

REQUIRE_APP_GATE = "false"
PREFER_DB_SECRETS = "true"

